markdown: redcarpet
pygments: true
permalink: /posts/:title

name: Sasa Ivetic
url: http://sivetic.github.io
description: Sasa Ivetic
twitter: sasaivetic
github: sivetic
gravatar_url: http://s.gravatar.com/avatar/57ea4c500d1fce1427b004558d988cc0